event_inherited();
spd = random_range(3 + 2, 5 + 2);
damaging = true;
damaging_cd_crt = 0;
image_alpha = 1;
roaming_time = 4;
roaming_time_crt = 0;
flash_alpha = 0;
disabled = false;
target = noone;
hacked = false;
hacked_cooldown_max = 60 * 20;
hacked_cooldown = 60 * 10;
foam_cooldown = 0;
foam_cooldown_max = 25;
can_pickup = false;
/// Create the path
path = path_add();
py = y;
depth = -10;
pickupRetical = sp_pickupReticleAttention;
alarm[0] = 20;